version: '3.0'

services:

  nginx:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/log:/var/log/container/
    depends_on:
      - php
    networks:
      - project

  php:
    build: ./docker/php
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/log:/var/log/container
    networks:
      - project

  composer:
    image: library/composer:latest
    command: ["composer", "install"]
    volumes:
      - ./:/app

networks:
  project:
    driver: bridge